PowerPlant.UI/Models/CreateWebDefinitionDataModel.cs
namespace PowerPlant.UI.Models
{
    public class CreateWebDefinitionDataModel
    {
        public string WebId { get; set; }
    }
}

PowerPlant.UI/Models/ErrorViewModel.cs
using System;

namespace PowerPlant.UI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PowerPlant.UI/Models/GetWebDefinitionDataModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PowerPlant.UI.Models
{
    public class GetWebDefinitionDataModel
    {
        public string WebId { get; set; }
        public DateTime StartTime { get; set; }
        public DateTime EndTime { get; set; }
    }
}

PowerPlant.UI/Models/WebDefinitionListModel.cs
using PowerPlant.Core.Entity;
using System.Collections.Generic;

namespace PowerPlant.UI.Models
{
    public class WebDefinitionListModel
    {
        public IEnumerable<WebDefinitionEntity> Entities { get; set; } = new List<WebDefinitionEntity>();
    }
}

PowerPlant.UI/Models/WebIdDataListModel.cs
using PowerPlant.Core.Entity;
using System.Collections.Generic;

namespace PowerPlant.UI.Models
{
    public class WebIdDataListModel
    {
        public IEnumerable<WebDefinitionEntity> Entities { get; set; } = new List<WebDefinitionEntity>();
    }
}

PowerPlant.UI/Controllers/WebDefinitionController.cs
using Flurl.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;
using PowerPlant.Application.Dto;
using PowerPlant.Core.Entity;
using PowerPlant.UI.Infrastructure;
using PowerPlant.UI.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Threading.Tasks;

namespace PowerPlant.UI.Controllers
{
    public class WebDefinitionController : Controller
    {
        private readonly ILogger<WebDefinitionController> _logger;
        private readonly ApiUrls _apiUrls;
        

        public WebDefinitionController(ILogger<WebDefinitionController> logger, IOptions<ApiUrls> apiUrls)
        {
            _logger = logger;
            _apiUrls = apiUrls.Value;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var url = $"{_apiUrls.WebDefinitionGetAll}";

            var result = await url.GetJsonAsync<List<WebDefinitionEntity>>();

            var model = new WebDefinitionListModel()
            {
                Entities = result
            };

            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> Create(CreateWebDefinitionDataModel dataModel)
        {
            var url = $"{_apiUrls.WebDefinitionSaveOrUpdate}";
            var dto = new WebDefinitionDto();

            dto.WebId = dataModel.WebId;
            dto.Timestamp = DateTime.Now;

            Random rand = new Random();
            dto.Good = rand.Next(0, 2) > 0;

            if(dto.Good == true)
            {
                dto.Value = rand.NextDouble().ToString();
            }
            else
            {
                dto.Value = JsonConvert.SerializeObject(new { errorMessage = "Somethings went wrong!!!" });
            }

            var result = await url.PostJsonAsync(dto).ReceiveJson<WebDefinitionDto>();

            return RedirectToAction("Index");

        }

        [HttpDelete("delete/{id}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            var url = $"{_apiUrls.WebDefinitionDelete}/{id}";
            var result = await url.DeleteAsync();

            return  Json("Deleted Successfully");
        }


        [HttpPost("edit/{id}")]
        public async Task<ActionResult> Edit(Guid id)
        {
            Random rand = new Random();

            var url = $"{_apiUrls.WebDefinitionSaveOrUpdate}";

            var entityUrl = $"{_apiUrls.WebDefinitionGetById}/{id}";
            var entityResult = await entityUrl.GetJsonAsync<WebDefinitionEntity>();

            entityResult.Good = rand.Next(0, 2) > 0;
            if (entityResult.Good == true)
            {
                entityResult.Value = rand.NextDouble().ToString();
            }
            else
            {
                entityResult.Value = JsonConvert.SerializeObject(new { errorMessage = "Somethings went wrong!!!" });
            }

            var dto = new WebDefinitionDto()
            {
                Id = entityResult.Id,
                WebId = entityResult.WebId,
                Timestamp = DateTime.Now,
                Good = entityResult.Good.Value,
                Value = entityResult.Value
            };
            var result = await url.PostJsonAsync(dto).ReceiveJson<WebDefinitionDto>();

            return RedirectToAction("Index");
        }












        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PowerPlant.UI/Controllers/WebIdDataController.cs
using Flurl.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using PowerPlant.Application.Dto;
using PowerPlant.Core.Entity;
using PowerPlant.UI.Infrastructure;
using PowerPlant.UI.Models;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace PowerPlant.UI.Controllers
{
    public class WebIdDataController : Controller
    {
        private readonly ApiUrls _apiUrls;

        public WebIdDataController(IOptions<ApiUrls> apiUrls)
        {
            _apiUrls = apiUrls.Value;
        }


        public IActionResult Index()
        {
            var model = new WebIdDataListModel();

            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> GetData(GetWebDefinitionDataModel dataModel)
        {
            var url = $"{_apiUrls.WebDefinitionGetAllByParameters}/{dataModel.WebId}?startTime={dataModel.StartTime:yyyy-MM-dd HH:mm:ss.fffffff}&endTime={dataModel.EndTime:yyyy-MM-dd HH:mm:ss.fffffff}";

            var result = await url.GetJsonAsync<List<WebDefinitionEntity>>();

            var model = new WebIdDataListModel()
            {
                Entities = result
            };

            return View("Index", model);
        }

        [HttpPost("save")]
        public async Task<IActionResult> Save(Guid id)
        {
            var getEntity = $"{_apiUrls.WebDefinitionGetById}/{id}";
            var entityResult = await getEntity.GetJsonAsync<WebDefinitionEntity>();

            var url = $"{_apiUrls.WebIdDataSave}";
            var dto = new WebIdDataDto();

            dto.WebId = entityResult.WebId;
            dto.Value = Convert.ToDecimal(entityResult.Value.Trim());

            var result = await url.PostJsonAsync(dto).ReceiveJson<WebIdDataDto>();
            return RedirectToAction("Index");

        }



    }
}

PowerPlant.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PowerPlant.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="WebDefinition" asp-action="Index">PowerPlant.UI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="WebDefinition" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="WebDefinition" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - PowerPlant.UI - <a asp-area="" asp-controller="WebDefinition" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    

    @RenderSection("Scripts", required: false)
</body>
</html>

PowerPlant.UI/Views/WebDefinition/Index.cshtml
@model WebDefinitionListModel
@{
    ViewData["Title"] = "Home Page";
}

@section Scripts
{
    <script>

        $('[data-btn="btnDelete"]').on('click', function (d) {
            d.preventDefault();
            debugger;
            $.ajax({
                url: $(this).attr('href'),
                method: 'DELETE',
                success: function (rslt) {
                    location.reload(true);
                },
                error: function (a, s, d) {
                    alert(a.responseText, "Error!");
                }
            });
        });

        $('[data-btn="btnEdit"]').on('click', function (e) {
            e.preventDefault();
            $.ajax({
                url: $(this).attr('href'),
                method: 'POST',
                success: function (rslt) {
                    location.reload(true);
                },
                error: function (a, s, d) {
                    alert(a.responseText, "Error!");
                }
            });
        });

    </script>
}




<div class="table-responsive mt-3">

    <form action="WebDefinition/Create" method="post" id="my_form">
        <label>WebId</label>
        <input type="text" id="webId" name="WebId" />
        <input type="submit" name="submit" value="Create" />
        <div id="server-results"></div>
    </form>

    <table class="table table-striped- table-bordered table-hover table-checkable" id="response-table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">WebId</th>
                <th scope="col">TimeStamp</th>
                <th scope="col">Good</th>
                <th scope="col">Value</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Entities.Any())
            {
                @foreach (var item in Model?.Entities.OrderByDescending(i => i.Timestamp))
                {
                    <tr data-id="@item.Id">
                        <td>@item.WebId</td>
                        <td>@item.Timestamp</td>
                        <td>@item.Good</td>
                        <td>@item.Value</td>
                        <td>
                            <a href="@Url.ActionLink("Edit","WebDefinition", new { id = item.Id})" class="btn btn-warning" data-btn="btnEdit" title="Edit">Edit</a>
                            <a href="@Url.ActionLink("Delete","WebDefinition", new { id = item.Id})" class="btn btn-danger" data-btn="btnDelete" title="Delete">Delete</a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

PowerPlant.UI/Views/WebIdData/Index.cshtml
@model WebIdDataListModel
@{
    ViewData["Title"] = "Home Page";
}

@section Scripts
{
    <script>
        $(function () {
            $("#startDate").datepicker();
            $("#endDate").datepicker();
        });


        $('[data-btn="btnSave"]').on('click', function (s) {
            s.preventDefault();
            $.ajax({
                url: $(this).attr('href'),
                method: 'POST',
                success: function (rslt) {
                    location.reload(true);
                },
                error: function (a, s, d) {
                    alert(a.responseText, "Error!");
                }
            });
        });

    </script>
}

<form action="WebIdData/GetData" method="post" id="my_form">
    <label>WebId</label>
    <input type="text" id="webId" name="WebId" />
    <label>Start Date</label>
    <input type="datetime" id="startDate" name="StartTime" />
    <label>End Date</label>
    <input type="datetime" id="endDate" name="EndTime" />
    <input type="submit" name="submit" value="Submit Form" />
    <div id="server-results"></div>
</form>


<div class="table-responsive mt-3">
    @if (Model.Entities.Any(i => i.Good == true))
    {
        <a href="@Url.ActionLink("Save","WebIdData", new { id = Model.Entities.Where(i => i.Good == true).OrderByDescending(i =>i.Timestamp).First().Id })" class="btn btn-info" data-btn="btnSave" title="Save">Save</a>
    }
    <table class="table table-striped- table-bordered table-hover table-checkable" id="response-table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">WebId</th>
                <th scope="col">TimeStamp</th>
                <th scope="col">Good</th>
                <th scope="col">Value</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Entities.Any())
            {
                @foreach (var item in Model.Entities.Where(i => i.Good == true).OrderByDescending(i => i.Timestamp))
                {
                    <tr data-id="@item.Id">
                        <td>@item.WebId</td>
                        <td>@item.Timestamp</td>
                        <td>@item.Good</td>
                        <td>@item.Value</td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>